canonical: https://gematik.de/fhir/isik/v2/Terminplanung
fhirVersion: 4.0.1
FSHOnly: true
applyExtensionMetadataToRoot: false
version: TC_2.0.5
dependencies:
  de.gematik.isik-basismodul: 2.0.5
  hl7.fhir.extensions.r5: 4.0.1
