canonical: https://gematik.de/fhir/isik
fhirVersion: 4.0.1
FSHOnly: true
applyExtensionMetadataToRoot: false
version: 4.0.0-rc
dependencies:
  de.gematik.isik-basismodul: 4.0.0-rc
  de.ihe-d.terminology: 3.0.0
  hl7.fhir.extensions.r5: 4.0.1
