canonical: https://gematik.de/fhir/isik/v3/Terminplanung
fhirVersion: 4.0.1
FSHOnly: true
applyExtensionMetadataToRoot: false
status: active
version: 3.0.4
dependencies:
  de.gematik.isik-basismodul: 3.0.4
  hl7.fhir.extensions.r5: 4.0.1

