canonical: https://gematik.de/fhir/ISiK/v2
fhirVersion: 4.0.1
FSHOnly: true
applyExtensionMetadataToRoot: false
version: "2.0.0-ballot3"
dependencies:
  de.gematik.isik-basismodul: 2.0.0-ballot3
  hl7.fhir.extensions.r5: 4.0.1
