canonical: https://gematik.de/fhir/isik/v2/Terminplanung
fhirVersion: 4.0.1
FSHOnly: true
applyExtensionMetadataToRoot: false
id: Implementierungsleitfaden ISiK-Modul Terminplanung
name: Implementierungsleitfaden ISiK-Modul Terminplanung
status: draft
version: "3.0.0-rc1"
publisher:
  name: Gematik GmbH
  url: https://www.gematik.de/
  email: ISiK@gematik.de
dependencies:
  de.gematik.isik-basismodul: 3.0.0-rc1
  hl7.fhir.extensions.r5: 4.0.1
