canonical: https://gematik.de/fhir/isik/v3/Terminplanung
fhirVersion: 4.0.1
FSHOnly: true
applyExtensionMetadataToRoot: false
version: 3.0.1
dependencies:
  de.gematik.isik-basismodul: 3.0.0
  hl7.fhir.extensions.r5: 4.0.1
