name: Use Tool Update Workflow

on:
  push:
    branches:
      - file-reference-basis

  # Allows you to run this workflow manually from the Actions tab      
  workflow_dispatch: 

jobs:
  call-tool-update:
    uses: gematik/spec-isik-basismodul/.github/workflows/main.yml@Update-dependency-trigger
    secrets:
      WORKFLOW_PERMISSION_GITHUB: ${{ secrets.WORKFLOW_PERMISSION_GITHUB }}