name: Use Tool Update Workflow

on:
  push:
    branches:
      - main-stufe-4

  # Allows you to run this workflow manually from the Actions tab      
  workflow_dispatch: 


jobs:
  call-tool-update:
    uses: gematik/spec-isik-basismodul/.github/workflows/main.yml@TC_4.0.1
    secrets:
      SIMPLIFIER_USERNAME: ${{ secrets.SIMPLIFIER_USERNAME }}
      SIMPLIFIER_PASSWORD: ${{ secrets.SIMPLIFIER_PASSWORD }}
      WORKFLOW_PERMISSION_GITHUB: ${{ secrets.WORKFLOW_PERMISSION_GITHUB }}      