name: Render All Diagrams

on:
  push:
    paths:
    - '**/Material/images/src/**/*.drawio'
    branches-ignore:
    - 'main**'
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repository
        uses: actions/checkout@v4

      # Generate the SVGs from DrawIO
      - name: Render DrawIO to SVG with predefined action
        uses: rlespinasse/drawio-export-action@v2
        with:
          path: ./Material/images/src/drawio/ 
          remove-page-suffix: true
          output: .
          format: svg
          action-mode: all

      # copies the created SVG files to the images/diagrams folder and deletes the drawio files
      - name: Move SVGs to target image folder
        run: |
          img_dir=Material/images/diagrams
          # Find all unique directories containing *.SVGs files under any /imgsrc/ folder
          FileNamePaths=$(find . -path "*/images/src/*/*.svg" -exec dirname {} \; | sort -u)
          for dir in $FileNamePaths
          do
            # Move SVGs to out directory
            find $dir -name "*.svg" -exec mv {} $img_dir \;
          done
      
      ## add and commit the new generated files
      #- name: Create Pull Request
      #  uses: peter-evans/create-pull-request@v5
      #  with:
      #    branch: auto/images-generation
      #    commit-message: Generated Images from source Code by GitHub Action
      #    title: Generated Images from GitHub Action
      #    assignees: ${{ github.actor }}
      #    reviewers: ${{ github.actor }}
      #    delete-branch: true
      #    labels: automated pr

      - name: Commit rendered files
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_user_name: GitHub Actions Bot
          commit_user_email: ActionBot@github.com
          commit_message: auto-generated diagrams by GitHub Action after source code change
